name: Create CMS PR
on:
  workflow_run:
    workflows: ["Create release on branch changes"]
    types:
      - completed

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hi Mikkel!"
