name: Create CMS PR
# on:
#   workflow_run:
#     workflows: ["Create release on branch changes"]
#     types:
#       - completed
on:
  push:
    branches:
      - develop

jobs:
  invoke-external-pr-workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://api.github.com/repos/reload/poc-dpl-cms-pr-trigger/dispatches'
        method: 'POST'
        customHeaders: '{"Accept": "application/vnd.github+json", "Authorization": "Bearer ${{ secrets.CMS_PR_CREATION_PAT }}" }'
        data: '{"event_type":"create_pr","client_payload":{"branch":"1731", "build_url":"https://github.com/danskernesdigitalebibliotek/dpl-react/releases/download/branch-user-registration-form-v2/dist-user-registration-form-v2.zip"}}'
